### PR TITLE
Tommys

### PR DESCRIPTION
**Pull request by sharanbngr**
Flag for adding strain type - Doppler or Strain

### CODE REVIEW

**Comment by kuan0020** [comment]
> @kuan0020 Can you add your various run folders to your .gitignore and re-push this?

Okay, did it work? I re-pushed run_blip.py with updated .gitignore. If it didn't work I'll have to push something else?

**Comment by criswellalexander** [comment]
It doesn't appear to have worked.

@sharanbngr is there a way to change the substance of the commit, or should I just reject & have him do a NEW, separate push?

**Comment by kuan0020** [comment]
Can you check again? I typed /[folder name] instead of [folder name]/ .

**Comment by sharanbngr** [comment]
@criswellalexander I think the right way is to merge again. Hang on let me do that ...

**Comment by criswellalexander** [comment]
Make sure you include the asterisk after the slash. That functions as a wildcard and tells git to ignore anything inside the specified folder. e.g.  MLDC_nside_analysis/*

**Comment by sharanbngr** [comment]
@kuan0020 Actually since you have already added your run files and we probably don't want them in git, I think you need to do `git rm` on them and commit again. I don't think just updating .gitignore would work here.

**Comment by kuan0020** [comment]
Can we just delete this request and I will push it again?

**Pull request closed without merging**
